# Data Preparation.

## Objectives
1. To practice identifying variable types within the dataset, determining the target variable as defined in the task, and examining variable distributions.
2. To acquaint oneself with the task forthcoming in the modeling stage.
3. To commence data exploration for the modeling phase.

## Components of the Practical Work
1. Load the dataset and become acquainted with it.
2. Explore the variables within the dataset.
3. Determine the variable types in the dataset.
4. Identify the target variable within the data and examine variable distributions.

## Key Emphasis:
- The program delivers correct answers based on the given dataset.
- Reasons for the chosen solutions are described when necessary.
- Code readability is prioritized: meaningful variable names are used, indentation and spacing rules are adhered to.
- The project repository contains meaningful commits, documenting specific implemented features; branches are named according to their purpose, and unnecessary files are not stored in the repository.


## Task
Starting from this lesson, I am commencing the exploration and preparation of data for the modeling stage.

I will be working with a small sample from a collection of used cars for sale in the United States, presented in the file data/vehicles_dataset.csv. Using this data, I will build the first classification model that determines the price category of a used car based on its characteristics.
In this practical work, I will load the dataset and begin its exploration.

## Dataset Description:
 - id: Record identifier.
 - url: URL of the sales record.
 - region: Region.
 - region_url: Region URL.
 - price: Price.
 - year: Year of manufacture.
 - manufacturer: Manufacturer.
 - model: Model.
 - condition: Condition.
 - cylinders: Number of cylinders.
 - fuel: Fuel type.
 - odometer: Mileage.
 - title_status: Title status.
 - transmission: Transmission type.
 - VIN: Vehicle identification number.
 - drive: Drive type.
 - size: Size.
 - type: Body type.
 - paint_color: Paint color.
 - image_url: Image URL.
 - description: Description.
 - county: County.
 - state: State.
 - lat: Latitude.
 - long: Longitude.
 - posting_date: Posting date of the sales advertisement.
 - price_category: Price category.

In [3]:
# Import necessary libraries
import pandas as pd

# Task 1. Loading the dataset and getting acquainted with it
## What needs to be done

First, it is necessary to load the dataset and become familiar with its characteristics.

1. Load the dataset from 'data/vehicles_dataset.csv' and display it.

In [4]:
df = pd.read_excel('C:\\Users\\Lietotajs\\Desktop\\ML Data Prep & Engineering\\1. Data Preparation\\Initial_Dataset\\vehicles_dataset.xlsx', )
df.head()

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,type,paint_color,image_url,description,county,state,lat,long,posting_date,price_category
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,good,NaN,...,pickup,silver,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,6 cylinders,...,SUV,black,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,NaN,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,good,NaN,...,sedan,NaN,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,NaN,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,NaN,NaN,...,wagon,white,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,NaN,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,new,4 cylinders,...,NaN,NaN,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,NaN,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium

2. Output the size of the dataset.

In [6]:
print(df.shape)

(10050, 27)

3. Output the list of dataset columns.

In [7]:
df.columns.tolist()

['id',
 'url',
 'region',
 'region_url',
 'price',
 'year',
 'manufacturer',
 'model',
 'condition',
 'cylinders',
 'fuel',
 'odometer',
 'title_status',
 'transmission',
 'VIN',
 'drive',
 'size',
 'type',
 'paint_color',
 'image_url',
 'description',
 'county',
 'state',
 'lat',
 'long',
 'posting_date',
 'price_category']

In [8]:
df.columns[1]

'url'

4. Output descriptive statistics for the entire dataset (be sure to specify the correct parameter for this).

In [9]:
df.describe()

,id,price,year,odometer,county,lat,long
count,1.005000e+04,1.005000e+04,10014.000000,1.000700e+04,0.0,9951.000000,9951.000000
mean,7.311544e+09,2.068429e+04,2010.917815,9.565719e+04,NaN,38.590164,-94.161564
std,4.475414e+06,1.243216e+05,9.697849,8.657948e+04,NaN,5.844756,18.123096
min,7.208550e+09,5.000000e+02,1915.000000,0.000000e+00,NaN,-67.144243,-158.069300
25%,7.308193e+09,7.900000e+03,2008.000000,3.899450e+04,NaN,34.830000,-110.447150
50%,7.312756e+09,1.574950e+04,2013.000000,8.837700e+04,NaN,39.285100,-87.999100
75%,7.315275e+09,2.799000e+04,2017.000000,1.370000e+05,NaN,42.427590,-80.830000
max,7.317090e+09,1.234568e+07,2022.000000,3.245000e+06,NaN,64.947500,173.885502

# Task 2. Exploration of Dataset Variables
## What needs to be done

After familiarizing yourself with the dataset, examine the values ​​that the variables with characteristics take.

Print in a loop for each column the column name, the number of unique values, and then the list of possible values along with their occurrence count in the dataset.

When displaying information for each characteristic, adhere to the template.



```
Characteristic: id
Number of unique values: 10000
List of values:
7303629857    2
7315995136    2
7316719393    2
7309842734    2
7307971804    2
             ..
7303843163    1
7315223900    1
7309940769    1
7309251820    1
7316428067    1
Name: id, Length: 10000, dtype: int64
```

In [10]:
for column in df.columns:
    print('Characteristic:', column)
    print('Number of unique values:', df[column].nunique())
    print('List of values:')
    print(df[column].value_counts(), '\n')

Characteristic: id
Number of unique values: 10000
List of values:
7316028281    2
7310693445    2
7310816094    2
7307639785    2
7312525382    2
             ..
7308265563    1
7309504220    1
7316238007    1
7311587823    1
7311960763    1
Name: id, Length: 10000, dtype: int64

Characteristic: url
Number of unique values: 10000
List of values:
https://roswell.craigslist.org/cto/d/artesia-1999-ford-f250-super-duty-super/7316028281.html         2
https://pueblo.craigslist.org/ctd/d/tempe-2017-ford-450-f450-450-drw-lariat/7310693445.html          2
https://monroe.craigslist.org/ctd/d/monroe-2019-infiniti-qx60-luxe/7310816094.html                   2
https://flint.craigslist.org/ctd/d/davison-2010-ford-150-xlt-supercrew/7307639785.html               2
https://charlotte.craigslist.org/cto/d/myrtle-beach-1947-mercury-hotrod-street/7312525382.html       2
                                                                                                    ..
https://mendocino.craigslist.org/cto/d/willits-2019-toyota-prius-prime-plus/7308265563.html          1
https://hudsonvalley.craigslist.org/ctd/d/waterbury-2005-toyota-camry-4dr-sdn-xle/7309504220.html    1
https://charlestonwv.craigslist.org/ctd/d/burkeville-1998-pierce-model-tilt-cab/7316238007.html      1
https://nashville.craigslist.org/ctd/d/murfreesboro-2016-chevrolet-equinox/7311587823.html           1
https://norfolk.craigslist.org/ctd/d/chesapeake-2017-ram-1500-crew-cab-big/7311960763.html           1
Name: url, Length: 10000, dtype: int64

Characteristic: region
Number of unique values: 393
List of values:
kansas city, MO          86
minneapolis / st paul    83
grand rapids             82
sarasota-bradenton       82
colorado springs         81
                         ..
gulfport / biloxi         1
southern WV               1
southwest MS              1
houma                     1
auburn                    1
Name: region, Length: 393, dtype: int64

Characteristic: region_url
Number of unique values: 405
List of values:
https://kansascity.craigslist.org     86
https://minneapolis.craigslist.org    83
https://grandrapids.craigslist.org    82
https://sarasota.craigslist.org       82
https://cosprings.craigslist.org      81
                                      ..
https://mattoon.craigslist.org         1
https://montana.craigslist.org         1
https://houma.craigslist.org           1
https://swv.craigslist.org             1
https://auburn.craigslist.org          1
Name: region_url, Length: 405, dtype: int64

Characteristic: price
Number of unique values: 2227
List of values:
6995     112
29990     91
7995      81
8995      76
9995      73
        ...
31422      1
40994      1
10781      1
38634      1
1575       1
Name: price, Length: 2227, dtype: int64

Characteristic: year
Number of unique values: 89
List of values:
2017.0    814
2018.0    814
2016.0    748
2013.0    704
2015.0    670
         ...
1937.0      1
1935.0      1
1954.0      1
1915.0      1
1958.0      1
Name: year, Length: 89, dtype: int64

Characteristic: manufacturer
Number of unique values: 39
List of values:
ford               1647
chevrolet          1298
toyota              784
jeep                491
honda               467
nissan              456
ram                 415
gmc                 361
bmw                 332
dodge               325
volkswagen          254
mercedes-benz       240
hyundai             225
subaru              211
audi                203
kia                 200
lexus               186
cadillac            184
chrysler            161
acura               150
buick               145
mazda               142
infiniti            118
lincoln             113
mitsubishi           82
mini                 73
volvo                67
pontiac              62
rover                59
jaguar               45
porsche              37
mercury              33
tesla                27
saturn               25
fiat                 23
alfa-romeo           14
ferrari               4
harley-davidson       4
datsun                2
Name: manufacturer, dtype: int64

Characteristic: model
Number of unique values: 3465
List of values:
f-150                        151
silverado 1500               110
1500                         101
camry                         77
silverado                     74
                            ...
sorrento lx v6                 1
sierra1500 crewcab 4x4         1
corolla se                     1
xc60 t6 inscription sport      1
a3 2.0t premium plus pzev      1
Name: model, Length: 3465, dtype: int64

Characteristic: condition
Number of unique values: 6
List of values:
good         3134
excellent    2429
like new      482
fair          179
new            31
salvage        13
Name: condition, dtype: int64

Characteristic: cylinders
Number of unique values: 8
List of values:
6 cylinders     2288
4 cylinders     1825
8 cylinders     1726
5 cylinders       46
10 cylinders      29
other             25
3 cylinders       13
12 cylinders       1
Name: cylinders, dtype: int64

Characteristic: fuel
Number of unique values: 5
List of values:
gas         8447
other        733
diesel       655
hybrid       108
electric      44
Name: fuel, dtype: int64

Characteristic: odometer
Number of unique values: 7006
List of values:
100000.0    51
1.0         42
200000.0    37
180000.0    37
140000.0    37
            ..
129119.0     1
41421.0      1
97487.0      1
165899.0     1
61943.0      1
Name: odometer, Length: 7006, dtype: int64

Characteristic: title_status
Number of unique values: 6
List of values:
clean         9568
rebuilt        171
salvage         92
lien            35
missing         16
parts only       2
Name: title_status, dtype: int64

Characteristic: transmission
Number of unique values: 3
List of values:
automatic    7737
other        1633
manual        635
Name: transmission, dtype: int64

Characteristic: VIN
Number of unique values: 5428
List of values:
1FMJU1JT1HEA52352    10
JN1AZ4EH8KM420880     8
1GCNCNEH7HZ118773     7
1FTMF1CP3GKD62143     7
5TFEM5F15KX140773     7
                     ..
1N6AD0EV8CC463906     1
1HTWLAZNX9J108397     1
3VWJL7AT5DM673430     1
WBA5A5C58FD512675     1
WP1AE2A28FLA50183     1
Name: VIN, Length: 5428, dtype: int64

Characteristic: drive
Number of unique values: 3
List of values:
4wd    3054
fwd    2563
rwd    1409
Name: drive, dtype: int64

Characteristic: size
Number of unique values: 4
List of values:
full-size      1476
mid-size        824
compact         458
sub-compact      67
Name: size, dtype: int64

Characteristic: type
Number of unique values: 13
List of values:
sedan          1981
SUV            1805
pickup         1071
truck           770
other           519
coupe           443
hatchback       414
wagon           255
van             227
convertible     204
mini-van        113
bus              22
offroad          21
Name: type, dtype: int64

Characteristic: paint_color
Number of unique values: 12
List of values:
white     1916
black     1473
silver    1041
red        741
blue       730
grey       601
green      173
custom     154
brown      144
yellow      53
orange      51
purple      10
Name: paint_color, dtype: int64

Characteristic: image_url
Number of unique values: 9081
List of values:
https://images.craigslist.org/00N0N_1xMPvfxRAIdz_0gw0co_600x450.jpg    191
https://images.craigslist.org/00R0R_lwWjXSEWNa7z_0x20oM_600x450.jpg     47
https://images.craigslist.org/00v0v_ihZKB5WEx8Rz_0gw0co_600x450.jpg      8
https://images.craigslist.org/00D0D_aqVh7XGmJcQz_0gw0co_600x450.jpg      8
https://images.craigslist.org/01111_l590CdXzJSoz_001001_600x450.jpg      7
                                                                      ...
https://images.craigslist.org/00S0S_gbHqFmRQh7kz_09a07K_600x450.jpg      1
https://images.craigslist.org/00z0z_45YWA8WkAUSz_0CI0t2_600x450.jpg      1
https://images.craigslist.org/01212_6JYMQ4lRmsHz_0gv0cn_600x450.jpg      1
https://images.craigslist.org/00m0m_d5zGKT3vPL4z_0lM0t2_600x450.jpg      1
https://images.craigslist.org/00O0O_gBihGEQxYTjz_0kE0fu_600x450.jpg      1
Name: image_url, Length: 9081, dtype: int64

Characteristic: description
Number of unique values: 9844
List of values:
PLEASE VIEW THE FREE CARFAX HISTORY REPORT AT OUR WEBSITE CARTERSCARSVT.COM OR CALL 802-891-6345 CHECK OUT OUR INVENTORY ON FACEBOOK!!!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       7
CREDIT CARS- $700.00 DOWN- RIGHT ON THE CORNER, RIGHT ON THE CREDIT!!  CALL US TODAY @ 352-204-2923 OR 352-204-2137. $700 DOWN!!!!!  CREDIT CHALLENGES??- NO PROBLEM- COME SEE US TODAY!  WE USE YOUR JOB AS YOUR CREDIT! ALL YOU NEED IS INCOME, PROOF OF INSURANCE, DRIVERS LICENSE, AND $700.00!!!  COME SEE US TODAY AT 320 NE 23RD AVENUE GAINESVILLE, FL 32609  WE ARE OPEN MONDAY- FRIDAY 9:00AM TO 7:00PM AND SATURDAY 9:00AM- 5:00PM  352-204-2137 OR 352-204-2137 CALL US TODAY TO SCHEDULE APPT!!  â­ Great Financing Options Available â­  âœ… Bad Credit? âœ… No Credit? âœ… First Time Buyer? âœ… We Work With Dozens Of Dealers To Get You Approved Fast Regardless Of Your Credit Situation.  ðŸš˜ Ready To Get Behind The Wheel Of Your New Car ðŸš˜  100% APPROVAL! We use your job as your credit!  We Guarantee It! No matter your financial situation, you will drive off the lot in a new car, today.  âœ… Bad Credit âœ… No Credit âœ… Repossession âœ… Foreclosure âœ… SSI âœ… Disability âœ… Government Assistance  YOU'RE APPROVED!  ðŸš˜ ðŸš˜  âœ… Huge Selection Of Quality Pre-Owned Cars âœ… Leave With Confidence âœ… Trade-In Your Car Today For A Great Discount   ðŸ“ Stop By Today                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      5

# Task 3. Determining Variable Types in the Dataset
## What needs to be done

After familiarizing yourself with the characteristics, fill in the table indicating the types of some variables. To do this, at the intersection of the variable name and the variable type, mark "X".



| Variable       | Discrete   | Continuous  | Categorical  |
|----------------|------------|-------------|--------------|
| id             | X          |             |              |
| region         |            |             |              |
| year           |            |             |              |
| manufacturer   |            |             |              |
| condition      |            |             |              |
| fuel           |            |             |              |
| odometer       |            |             |              |
| title_status   |            |             |              |
| transmission   |            |             |              |
| VIN            |            |             |              |
| drive          |            |             |              |
| paint_color    |            |             |              |
| state          |            |             |              |
| price_category |            |             |              |

In [11]:
varble_type_dict = {'Variable': [], 'Discrete': [], 'Continuous': [], 'Qualitative': []}
for elem in df.columns:
    if pd.api.types.is_integer_dtype(df[elem].values.dtype):
        varble_type_dict['Variable'].append(elem),
        varble_type_dict['Discrete'].append('X'),
        varble_type_dict['Continuous'].append(' '), 
        varble_type_dict['Qualitative'].append(' ')
    elif pd.api.types.is_string_dtype(df[elem].values.dtype):
        varble_type_dict['Variable'].append(elem),
        varble_type_dict['Discrete'].append(' '),
        varble_type_dict['Continuous'].append(' '), 
        varble_type_dict['Qualitative'].append('X')
    elif pd.api.types.is_float_dtype(df[elem].values.dtype):
        varble_type_dict['Variable'].append(elem),
        varble_type_dict['Discrete'].append(' '),
        varble_type_dict['Continuous'].append('X'), 
        varble_type_dict['Qualitative'].append(' ')

df2 = pd.DataFrame(varble_type_dict)
df2.set_index('Variable', inplace=True)
df2

               Discrete Continuous Qualitative
Variable
id                    X
url                                          X
region                                       X
region_url                                   X
price                 X
year                             X
manufacturer                                 X
model                                        X
condition                                    X
cylinders                                    X
fuel                                         X
odometer                         X
title_status                                 X
transmission                                 X
VIN                                          X
drive                                        X
size                                         X
type                                         X
paint_color                                  X
image_url                                    X
description                                  X
county                           X
state                                        X
lat                              X
long                             X
posting_date                                 X
price_category                               X

### Task 4. Determining the Target Variable in the Data and Variable Distributions
**What needs to be done**

1. Based on the task, determine which column contains the target variable.

**Answer:** Price Category - target variable

2. Output the proportion of occurrence in the sample for each value of the target variable.

In [7]:
total=df['price_category'].count()
CategoryShares = {'Category': [],'Share': []}

for i in df['price_category'].unique():
    (CategoryShares['Category']).append(i) 
    (CategoryShares['Share']).append((df[df['price_category'] == i].shape[0] / total).round(4))
    
df3 = pd.DataFrame(CategoryShares)
df3

  Category   Share
0     high  0.3497
1   medium  0.3278
2      low  0.3226

3. Once again, examine the proportion or count of occurrences of each value of the target variable in the sample and write down what distribution it represents. It is possible to determine the distribution of the target variable values in this case even without a graph.

**Answer:** Uniform distribution